export const PLACES_DATA = [
  {
    id: 1,
    name: "Auditorio, Paraninfo Alfonso Aguilar Ruilova.",
    title: "Auditorio, Paraninfo Alfonso Aguilar Ruilova",
    subtitle: "Paraninfo Alfonso Aguilar Ruilova.",
    description:
      "Eventos con tecnología de alta calidad multiconexión streaming.  Videoconferencias con sistema de audio y sonido profesional.",
    imgUrl: "/public/carousel-1.svg",
    available: true,
    status: "Disponible", // Disponible, No disponible, en mantenimiento, en uso
    rates: {
      pricePerHour: 250,
      halfDayPrice: 1000,
      fullDayPrice: 2000,
      weekendDaySurchargePercent: 15,
    },
    area: 300,
    features: [
      "Una pantalla gigante de 35 módulos de 4.48 metros de largo por 2,40 será instalada",
      "Sistema de alta calidad para videoconferencias y programas",
      "El sistema está conformado por 40 equipos para el montaje",
    ],
    internalServices: {
      wifi: true,
      wifiPricePerHourAditional: 10,
      airConditioner: true,
      airConditionerPricePerHourAditional: 5,
      projector: true,
      projectorPricePerHourAditional: 15,
      soundSystem: true,
      soundSystemPricePerHourAditional: 20,
      display: true,
      displayPricePerHourAditional: 5,
      bathrooms: true,
      medicalAtention: true,
      priceMedicalAtention: 50,
      parking: true,
      security: true,
      cleaning: true,
    },
    technicalData: {
      capacity: 637,
      dimentions: {
        widthMeters: 20,
        heightMeters: 15,
        depthMeters: 10,
        squareMeters: 300,
      },
    },
    additionalServices: [
      {
        serviceName: "Catering",
        available: true,
      },
      {
        serviceName: "Transporte",
        available: true,
      },
      {
        serviceName: "Guias",
        available: true,
      },
      {
        serviceName: "Publicidad",
        available: true,
      },
    ],
  },
  {
    id: 2,
    name: "Plaza Cultural Centenario.",
    title: "Plaza Cultural Centenario.",
    subtitle: "Plaza Cultural Centenario.",
    description:
      "El espacio perfecto al aire libre para congregar a un gran público. La Cultura Manteña y la brisa marina en su máximo esplendor.",
    imgUrl: "/public/carousel-2.svg",
    available: true,
    status: "Disponible", // Disponible, No disponible, en mantenimiento, en uso
    rates: {
      pricePerHour: 100,
      halfDayPrice: 400,
      fullDayPrice: 800,
      weekendDaySurchargePercent: 10,
    },
    area: 300,
    features: [
      "Área de construcción de 5.471 m²",
      "Mural de 150 m²",
      "Obras  subterráneas; hidrosanitario, cableado eléctrico y redes de agua potable",
      "Iluminación con 30 postes de acero reforzado con luces LED",
      "Espacios multiusos (Será, además,  parqueadero cuando no haya eventos culturales)",
      "La cultura Manteña en su esplendor",
      "La silla Manteña, Cuatro incensiarios, Símbolos manteños que hacen referencia a los cuatro elementos: agua, aire, tierra y fuego",
    ],
    internalServices: {
      wifi: true,
      wifiPricePerHourAditional: 10,
      airConditioner: false,
      airConditionerPricePerHourAditional: 5,
      projector: false,
      projectorPricePerHourAditional: 15,
      soundSystem: false,
      soundSystemPricePerHourAditional: 20,
      display: false,
      displayPricePerHourAditional: 5,
      bathrooms: true,
      parking: true,
      medicalAtention: true,
      priceMedicalAtention: 50,
      security: true,
      cleaning: true,
    },
    technicalData: {
      capacity: 500,
      dimentions: {
        widthMeters: 20,
        heightMeters: 15,
        depthMeters: 10,
        squareMeters: 300,
      },
    },
    additionalServices: [
      {
        serviceName: "Catering",
        available: true,
      },
      {
        serviceName: "Transporte",
        available: true,
      },
      {
        serviceName: "Guias",
        available: true,
      },
      {
        serviceName: "Publicidad",
        available: true,
      },
    ],
  },
  {
    id: 3,
    name: "Cinema Auditorio.",
    title: "Cinema Auditorio.",
    subtitle: "Cinema Auditorio.",
    description:
      "Acogedor y envolvente espacio, ideal para cine foro, conferencias y toda la experiencia del 7 mo arte en 124 butacas.",
    imgUrl: "/public/carousel-3.svg",
    available: false,
    status: "No disponible", // Disponible, No disponible, en mantenimiento, en uso
    rates: {
      pricePerHour: 150,
      halfDayPrice: 600,
      fullDayPrice: 1200,
      weekendDaySurchargePercent: 10,
    },
    area: 100,
    features: [
      "Pantalla LED central, que abarca impresionantes dimensiones de 6.40 metros de largo por 5 metros de ancho. Este equipo avanzado consta de 480 módulos LED de alta resolución, complementados por un sistema de sonido excepcional que garantiza una calidad de audio uniforme y envolvente para los 124 asistentes que puede albergar la sala que está climatizada, además cuenta con baterias sanitarias y acceso a internet",
    ],
    internalServices: {
      wifi: true,
      wifiPricePerHourAditional: 10,
      airConditioner: true,
      airConditionerPricePerHourAditional: 5,
      projector: true,
      projectorPricePerHourAditional: 15,
      soundSystem: true,
      soundSystemPricePerHourAditional: 20,
      display: true,
      displayPricePerHourAditional: 5,
      bathrooms: true,
      parking: true,
      medicalAtention: true,
      priceMedicalAtention: 50,
      security: true,
      cleaning: true,
    },
    technicalData: {
      capacity: 124,
      dimentions: {
        widthMeters: 10,
        heightMeters: 10,
        depthMeters: 10,
        squareMeters: 296,
      },
    },
    additionalServices: [
      {
        serviceName: "Catering",
        available: true,
      },
      {
        serviceName: "Transporte",
        available: true,
      },
      {
        serviceName: "Guias",
        available: true,
      },
      {
        serviceName: "Publicidad",
        available: true,
      },
    ],
  },
  {
    id: 4,
    name: "Estadio Universitario.",
    title: "Estadio Universitario.",
    subtitle: "Estadio Universitario.",
    description:
      "El epicentro de la pasión deportiva y los grandes espectáculos del Pacífico.",
    imgUrl: "/public/carousel-4.svg",
    available: true,
    status: "Disponible", // Disponible, No disponible, en mantenimiento, en uso
    rates: {
      pricePerHour: 500,
      halfDayPrice: 2000,
      fullDayPrice: 4000,
      weekendDaySurchargePercent: 20,
    },
    area: 5000,
    features: [
      "Instalaciones Modernas: Asientos cómodos y visibilidad perfecta.",
      "Eventos Deportivos: Desde partidos de fútbol universitario hasta competencias atléticas, el escenario ideal para el talento deportivo.",
      "Conciertos y Espectáculos: Acoge a artistas de renombre y eventos culturales que enriquecen nuestra comunidad.",
      "Ubicación Estratégica: En el corazón del campus, con fácil acceso y amplias opciones de estacionamiento.",
      "Seguridad y Comodidad: Personal capacitado y servicios de seguridad para que disfrutes sin preocupaciones.",
    ],
    internalServices: {
      wifi: true,
      wifiPricePerHourAditional: 10,
      airConditioner: false,
      airConditionerPricePerHourAditional: 0,
      projector: false,
      projectorPricePerHourAditional: 0,
      soundSystem: false,
      soundSystemPricePerHourAditional: 20,
      display: false,
      displayPricePerHourAditional: 0,
      bathrooms: true,
      parking: true,
      medicalAtention: true,
      priceMedicalAtention: 50,
      security: true,
      cleaning: true,
    },
    technicalData: {
      capacity: 1000,
      dimentions: {
        widthMeters: 100,
        heightMeters: 50,
        depthMeters: 10,
        squareMeters: 5000,
      },
    },
    additionalServices: [
      {
        serviceName: "Catering",
        available: true,
      },
      {
        serviceName: "Transporte",
        available: true,
      },
      {
        serviceName: "Guias",
        available: true,
      },
      {
        serviceName: "Publicidad",
        available: true,
      },
    ],
  },
  {
    id: 5,
    name: "Laboratorio Gastronómico.",
    title: "Laboratorio Gastronómico.",
    subtitle: "Laboratorio Gastronómico.",
    description:
      "El Lugar donde tu paladar emprende un viaje ancestral a nuestra gastronomía. El mejor servicio, de la mano de expertos y sus estudiantes.",
    imgUrl: "/public/carousel-5.svg",
    available: true,
    status: "Disponible", // Disponible, No disponible, en mantenimiento, en uso
    rates: {
      pricePerHour: 50,
      halfDayPrice: 200,
      fullDayPrice: 400,
      weekendDaySurchargePercent: 10,
    },
    area: 100,
    features: [
      "Nuestro personal especializado está listo para atenderte como te mereces. Deléitate con platos preparados por expertos gastronómicos, en una colaboración única entre docentes y estudiantes. ¡Ven y vive una experiencia culinaria extraordinaria!",
    ],
    internalServices: {
      wifi: true,
      wifiPricePerHourAditional: 10,
      airConditioner: true,
      airConditionerPricePerHourAditional: 5,
      projector: true,
      projectorPricePerHourAditional: 15,
      soundSystem: true,
      soundSystemPricePerHourAditional: 20,
      display: true,
      displayPricePerHourAditional: 5,
      bathrooms: true,
      parking: true,
      security: true,
      medicalAtention: true,
      priceMedicalAtention: 50,
      cleaning: true,
    },
    technicalData: {
      capacity: 120,
      dimentions: {
        widthMeters: 10,
        heightMeters: 10,
        depthMeters: 10,
        squareMeters: 150,
      },
    },
    additionalServices: [
      {
        serviceName: "Catering",
        available: true,
      },
      {
        serviceName: "Transporte",
        available: true,
      },
      {
        serviceName: "Guias",
        available: true,
      },
      {
        serviceName: "Publicidad",
        available: true,
      },
    ],
  },
  {
    id: 6,
    name: "Sala de Concierto Horacio Hidrovo P.",
    title: "Sala de Concierto Horacio Hidrovo P.",
    subtitle: "Sala de Concierto Horacio Hidrovo P.",
    description:
      "Un espacio para disfrutar de hermosas sonatas y cultura musical.",
    imgUrl: "/public/carousel-1.svg",
    available: true,
    status: "Disponible", // Disponible, No disponible, en mantenimiento, en uso
    rates: {
      pricePerHour: 200,
      halfDayPrice: 800,
      fullDayPrice: 1600,
      weekendDaySurchargePercent: 10,
    },
    area: 150,
    features: [
      "Sumérgete en una experiencia sonora inigualable en nuestra Sala de Conciertos, el escenario perfecto para cada nota y cada emoción. Este espacio está diseñado para elevar cada presentación musical a un nuevo nivel. Ya sea para conciertos íntimos o grandes espectáculos, nuestra sala garantiza una experiencia inolvidable para artistas y espectadores.",
    ],
    internalServices: {
      wifi: true,
      wifiPricePerHourAditional: 10,
      airConditioner: true,
      airConditionerPricePerHourAditional: 5,
      projector: true,
      projectorPricePerHourAditional: 15,
      soundSystem: true,
      soundSystemPricePerHourAditional: 20,
      display: true,
      displayPricePerHourAditional: 5,
      bathrooms: true,
      parking: true,
      security: true,
      cleaning: true,
    },
    technicalData: {
      capacity: 200,
      dimentions: {
        widthMeters: 15,
        heightMeters: 10,
        depthMeters: 10,
        squareMeters: 150,
      },
    },
    additionalServices: [
      {
        serviceName: "Catering",
        available: true,
      },
      {
        serviceName: "Transporte",
        available: true,
      },
      {
        serviceName: "Guias",
        available: true,
      },
      {
        serviceName: "Publicidad",
        available: true,
      },
    ],
  },
  {
    id: 7,
    name: "Sala de Capacitaciones, Carrea de Agropecuaria.",
    title: "Sala de Capacitaciones",
    subtitle: "Carrera de Agropecuaria.",
    description:
      "Espacio Ideal para la desconexión del día a día y sumergirse en capacitaciones multidisciplinares.",
    imgUrl: "/public/carousel-2.svg",
    available: true,
    status: "En mantenimiento", // Disponible, No disponible, en mantenimiento, en uso
    rates: {
      pricePerHour: 100,
      halfDayPrice: 400,
      fullDayPrice: 800,
      weekendDaySurchargePercent: 10,
    },
    area: 100,
    features: [
      "El Salón de Reuniones perfecto para tus encuentros profesionales. Diseñado para fomentar la colaboración y la productividad, nuestro espacio está equipado con todo lo que necesitas para llevar tus reuniones al siguiente nivel.",
      "Tecnología Moderna: Pantalla de alta definición y sistemas de videoconferencia para presentaciones impecables.",
    ],
    internalServices: {
      wifi: true,
      wifiPricePerHourAditional: 10,
      airConditioner: true,
      airConditionerPricePerHourAditional: 5,
      projector: true,
      projectorPricePerHourAditional: 15,
      soundSystem: true,
      soundSystemPricePerHourAditional: 20,
      display: true,
      displayPricePerHourAditional: 5,
      chairs: 50,
      tables: 2,
      bathrooms: 2,
      bar: false,
      kitchen: false,
      parking: true,
      security: true,
      cleaning: true,
    },
    technicalData: {
      capacity: 50,
      dimentions: {
        widthMeters: 10,
        heightMeters: 10,
        depthMeters: 10,
        squareMeters: 100,
      },
    },
    additionalServices: [
      {
        serviceName: "Catering",
        available: true,
      },
      {
        serviceName: "Transporte",
        available: true,
      },
      {
        serviceName: "Guias",
        available: true,
      },
      {
        serviceName: "Publicidad",
        available: true,
      },
    ],
  },
  {
    id: 8,
    name: "Auditorio, Carrera de Odontología.",
    title: "Auditorio",
    subtitle: "Carrera de Odontología",
    description:
      "Acogedor espacio donde la conexión entre el emisor y receptor es más efectiva.",
    imgUrl: "/public/carousel-3.svg",
    available: false,
    status: "No disponible", // Disponible, No disponible, en mantenimiento, en uso
    rates: {
      pricePerHour: 150,
      halfDayPrice: 600,
      fullDayPrice: 1200,
      weekendDaySurchargePercent: 10,
    },
    area: 100,
    features: [
      "Área de construcción de 127,9 m²",
      "Instalaciones Modernas: Asientos cómodos, visibilidad perfecta y tecnología avanzada para una experiencia superior.",
    ],
    internalServices: {
      wifi: true,
      wifiPricePerHourAditional: 10,
      airConditioner: true,
      airConditionerPricePerHourAditional: 5,
      projector: true,
      projectorPricePerHourAditional: 15,
      soundSystem: true,
      soundSystemPricePerHourAditional: 20,
      display: true,
      displayPricePerHourAditional: 5,
      parking: true,
      security: true,
      cleaning: true,
    },
    technicalData: {
      capacity: 100,
      dimentions: {
        widthMeters: 10,
        heightMeters: 10,
        depthMeters: 10,
        squareMeters: 100,
      },
    },
    additionalServices: [
      {
        serviceName: "Catering",
        available: true,
      },
      {
        serviceName: "Transporte",
        available: true,
      },
      {
        serviceName: "Guias",
        available: true,
      },
      {
        serviceName: "Publicidad",
        available: true,
      },
    ],
  },
  {
    id: 9,
    name: "Auditorio, Carrera de Comunicación.",
    title: "Auditorio",
    subtitle: "Carrera de Comunicación",
    description: "Donde las ideas se convierten en grandes presentaciones.",
    imgUrl: "/public/carousel-4.svg",
    available: true,
    status: "Disponible", // Disponible, No disponible, en mantenimiento, en uso
    rates: {
      pricePerHour: 200,
      halfDayPrice: 800,
      fullDayPrice: 1600,
      weekendDaySurchargePercent: 10,
    },
    area: 150,
    features: [
      "Tecnología Moderna: Pantallas de alta definición, proyectores y sistemas de videoconferencia para presentaciones impecables.",
      "Confort y Estilo: Asientos ergonómicos y un diseño elegante que garantizan comodidad durante largas sesiones.",
      "Espacios Flexibles: Configuraciones adaptables para reuniones pequeñas o grandes conferencias.",
      "Ambiente Profesional: Iluminación natural y ambiente tranquilo para maximizar la concentración y la creatividad.",
    ],
    internalServices: {
      wifi: true,
      wifiPricePerHourAditional: 10,
      airConditioner: true,
      airConditionerPricePerHourAditional: 5,
      projector: true,
      projectorPricePerHourAditional: 15,
      soundSystem: true,
      soundSystemPricePerHourAditional: 20,
      display: true,
      displayPricePerHourAditional: 5,
      parking: true,
      security: true,
      cleaning: true,
    },
    technicalData: {
      capacity: 150,
      dimentions: {
        widthMeters: 15,
        heightMeters: 10,
        depthMeters: 10,
        squareMeters: 150,
      },
    },
    additionalServices: [
      {
        serviceName: "Catering",
        available: true,
      },
      {
        serviceName: "Transporte",
        available: true,
      },
      {
        serviceName: "Guias",
        available: true,
      },
      {
        serviceName: "Publicidad",
        available: true,
      },
    ],
  },
];

localStorage.setItem("placesData", JSON.stringify(PLACES_DATA));
